version: "3"
services:
  flask:
    build: .
    environment:
      FLASK_DEBUG: True
    ports:
      - "8000:5000"
    depends_on:
      - db
    volumes:
      - .:/opt/app/lustra
    entrypoint: ["flask", "--app", "src/main", "run", "--host", "0.0.0.0"]
#  mariadb:
#    image: "mariadb:10.10.2-jammy"
#    environment:
#      MARIADB_ROOT_USER: "petelya"
#      MARIADB_ROOT_PASSWORD: "petelya"
